import { createServerClient } from "@supabase/ssr";
import { type NextRequest, NextResponse } from "next/server";

// Routes reachable without being logged in / approved.
// - /login, /auth/confirm, /auth/reset-password: the auth flow itself
//   (confirm/reset-password must stay public — their token_hash verification
//   runs before any session cookie exists, so gating them would bounce the
//   confirmation/recovery link straight to /login and drop the token_hash
//   query param)
// - /pending: screen shown to logged-in-but-not-yet-approved accounts
// - /api/auth/email: Supabase's Send Email Hook calls this server-to-server
//   (no user session) — redirecting it to /login would break every auth mail.
// - /manifest.webmanifest, /icon, /apple-icon, /icons/*: PWA metadata — the
//   browser tab favicon must render on /login itself, and Chrome/Safari need
//   to fetch these to offer "Add to Home Screen" even before the user signs in.
// - /sw.js, /offline: service worker + its offline fallback page (see
//   public/sw.js). ServiceWorkerRegister.tsx registers /sw.js from the root
//   layout, which also renders on /login — gating it would turn every
//   registration attempt by a logged-out visitor into a redirect response
//   instead of the actual script. /offline is served by the service worker
//   straight from its cache with no network round trip when truly offline,
//   so this gate normally never sees it — but must not bounce it to /login
//   on the rare direct/online hit.
const PUBLIC_PATHS = [
  "/login",
  "/auth/confirm",
  "/auth/reset-password",
  "/pending",
  "/api/auth/email",
  "/manifest.webmanifest",
  "/icon",
  "/apple-icon",
  "/icons",
  "/sw.js",
  "/offline",
];

function isPublicPath(pathname: string) {
  return PUBLIC_PATHS.some((p) => pathname === p || pathname.startsWith(`${p}/`));
}

function redirectTo(request: NextRequest, path: string, cookieSource: NextResponse) {
  const url = request.nextUrl.clone();
  url.pathname = path;
  url.search = "";
  const response = NextResponse.redirect(url);
  cookieSource.cookies.getAll().forEach((cookie) => response.cookies.set(cookie));
  return response;
}

// Refreshes the Supabase session on every request and gates access:
// visitors are redirected to /login, logged-in accounts that aren't
// yet approved by an admin are redirected to /pending.
//
// `nonce`/`csp` (generated by proxy.ts) must reach downstream Server
// Components via headers().get("x-nonce") — done by rebuilding the
// `request: { headers }` override from the request's *current* headers on
// every NextResponse.next() call below, not a header snapshot taken once
// up front. request.cookies.set() (in setAll) mutates request.headers'
// Cookie value in place; rebuilding fresh each time is what carries that
// refreshed session cookie into the same request's downstream render —
// a stale pre-cloned Headers object would silently serve the old session.
export const updateSession = async (request: NextRequest, nonce: string, csp: string) => {
  const nextWithNonce = () => {
    const headers = new Headers(request.headers);
    headers.set("x-nonce", nonce);
    headers.set("Content-Security-Policy", csp);
    return NextResponse.next({ request: { headers } });
  };

  let supabaseResponse = nextWithNonce();

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value }) =>
            request.cookies.set(name, value)
          );
          supabaseResponse = nextWithNonce();
          cookiesToSet.forEach(({ name, value, options }) =>
            supabaseResponse.cookies.set(name, value, options)
          );
        },
      },
    }
  );

  // IMPORTANT: calling getUser() is what triggers the token refresh.
  // Do not remove this line.
  const { data: { user } } = await supabase.auth.getUser();

  const pathname = request.nextUrl.pathname;
  if (isPublicPath(pathname)) {
    return supabaseResponse;
  }

  if (!user) {
    return redirectTo(request, "/login", supabaseResponse);
  }

  const { data: profile } = await supabase
    .from("profiles")
    .select("status")
    .eq("id", user.id)
    .single();

  if (profile?.status !== "approved") {
    return redirectTo(request, "/pending", supabaseResponse);
  }

  return supabaseResponse;
};
